CREATE TABLE
  TBL_OFEI1204 (
    Id SERIAL PRIMARY KEY,
    Agente VARCHAR (100),
    Planta VARCHAR (100),
    Hora_1 FLOAT,
    Hora_2 FLOAT,
    Hora_3 FLOAT,
    Hora_4 FLOAT,
    Hora_5 FLOAT,
    Hora_6 FLOAT,
    Hora_7 FLOAT,
    Hora_8 FLOAT,
    Hora_9 FLOAT,
    Hora_10 FLOAT,
    Hora_11 FLOAT,
    Hora_12 FLOAT,
    Hora_13 FLOAT,
    Hora_14 FLOAT,
    Hora_15 FLOAT,
    Hora_16 FLOAT,
    Hora_17 FLOAT,
    Hora_18 FLOAT,
    Hora_19 FLOAT,
    Hora_20 FLOAT,
    Hora_21 FLOAT,
    Hora_22 FLOAT,
    Hora_23 FLOAT,
    Hora_24 FLOAT
  );
